name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the version from package.json
      id: get_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "::set-output name=version::$version"

    - name: Create GitHub tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=${{ steps.get_version.outputs.version }}
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git tag -a "v$version" -m "Release version $version"
        git push origin "v$version"

    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ steps.get_version.outputs.version }}"
        release_name: "v${{ steps.get_version.outputs.version }}"
        body: "Release of version ${{ steps.get_version.outputs.version }}"
        draft: false
        prerelease: false
